version: '3.8'
services:
  db:
    image: mariadb:11
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: docker
      MYSQL_USER: root
      MYSQL_PASSWORD: Med@c
    ports:
      - "3308:3306"  
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  web:
    image: php:8.2-apache
    depends_on:
      - db
    volumes:
      - ./php/html:/var/www/html
    ports:
      - "8080:80"
    environment:
      PHP_DISPLAY_ERRORS: 1

volumes:
  db_data:

